function data = importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read
% Copyright (c) 2016, MathWorks, Inc. 
%  Auto-generated by MATLAB on 26-Aug-2016 09:52:24

% Import the file
data = importdata(fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(data);
for i = 1:length(vars)
    assignin('base', vars{i}, data.(vars{i}));
end

